---
- name: Creating\Terminating EC2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - ec2:
       key_name: vjadmin
       instance_type: t2.micro
       image: ami-0ce933e2ae91880d3
       wait: yes
       region: ap-south-1
       group: vjadmin_sg
       count: 1
       vpc_subnet_id: subnet-3f83aa57
       assign_public_ip: yes
       wait: yes
       wait_timeout: 180
  tasks:
    - ec2:
       state: 'absent'
       instance_ids: '{{ ec2.instance_ids }}' 
       region: ap-south-1 
